### PR TITLE
RMA, AMO, Reduction edits

### PR DESCRIPTION
**Pull request by shamisp**
* Adding macro for subsubsubsection
* Moving blocking and non_blocking RMA into one subsubsection
* Moving blocking and non_blocking AMO into one subsubsection
* Updating AMO introduction to reflect support for non_blocking
operations
* Reduction paragraph was replaced with subsubsubsection to make the
text consistent

Signed-off-by: Pavel Shamis (Pasha) <pasharesearch@gmail.com>

### CODE REVIEW

**Comment by shamisp** [comment]
This is continuation of  https://github.com/openshmem-org/specification/pull/362

**Comment by shamisp** [comment]
Adding @nspark @manjugv

**Comment by shamisp** [comment]
Adding @jdinan

**Review by jdinan — COMMENTED** [review]
Looks great!

**Review by jdinan — APPROVED** [review]

**Comment by manjugv** [comment]
Looks good.

**Pull request merged**
