### PR TITLE
Undefined behavior clause added for invalid ctx

### PR DESCRIPTION
**Pull request by wrrobin**
Signed-off-by: Md <md.rahman@intel.com>

### CODE REVIEW

**Review by shamisp — APPROVED** [review]

**Comment by shamisp** [comment]
Adding @manjugv for review. Looks good for me.

**Comment by manjugv** [comment]
@wrrobin The changes looks good. 

I'm wondering, given that we are repeating this sentence everywhere, is this a candidate for moving to the section preamble ? 

We could add something like this. Please feel free edit the text to suit the style/tone.

`Each of the OpenSHMEM RMA routine specified in the section has two variants. First variant where the context handle is explicitly passed as an argument. In this variant, the operation is performed on the specified context. If the context handle does not correspond to a valid context, the behavior is undefined. In the second variant, the context handle is not explicitly passed, and the operations are performed on a default context. `

**Comment by wrrobin** [comment]
@manjugv This PR added the texts in Atomic NBI section (9.9) and put-signal section (9.10). Currently, 9.9 does not have any texts in the preamble. Are you suggesting to add your proposed text in both 9.9 and 9.10? 
Actually, this particular text proposed in the PR is already available in other APIs such as blocking RMA and AMO routines. One option is to add your proposed text to each of those sections preambles and remove the repeated text from all the API descriptions. The other option is to make the change currently only for 9.9 and 9.10 and leave the rest of the occurrences as it is for future changes. Please let me know if option 1 is a valid choice for section committee edits.

**Comment by manjugv** [comment]
@wrrobin "One option is to add your proposed text to each of those sections preambles and remove the repeated text from all the API descriptions. " - This was my proposal. It seems like we can remove the repetitive text.

**Comment by wrrobin** [comment]
@manjugv Ok. I will add your suggested paragraph to 9.6, 9.7, 9.8, 9.9, 9.10 section preambles and remove the one-line text from the API descriptions.

**Comment by manjugv** [comment]
@wrrobin Pasha has a patch where the RMA blocking and non-blocking operations are merged into a single section. If you add your patch on top of it, you need to add the paragraph only once and remove the repeated text. @shamisp ?

**Comment by shamisp** [comment]
@manjugv the patch is merged into ram/1.5.0

**Comment by shamisp** [comment]
https://github.com/shamisp/specification/pull/1

**Comment by wrrobin** [comment]
@shamisp @manjugv Thanks for the help. I have added the changes. Can you please re-review and let me know if you see any concern. 
One note, currently, signaling operations section (9.8) is kept in main_spec.tex. Do we have plans to move this out as a separate file? For the time being, I have added the texts in main_spec.tex.

**Comment by manjugv** [comment]
👍

**Comment by shamisp** [comment]
@wrrobin can you please squash so you have only one commit. 
Please rebase you patch on top of head of sec/rma/1.5.0

**Comment by wrrobin** [comment]
@shamisp Please check and let me know if things look ok.

**Comment by shamisp** [comment]
Looks good to me. Thanks for doing this.

**Pull request merged**
